{
 "title": "FlyHorizons - Health Checks & Heartbeats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "User Service MSSQL Database Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mssql_db_health{job=\"user-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Service RabbitMQ Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_health{job=\"user-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Booking Service MSSQL Database Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mssql_db_health{job=\" booking-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Booking Service RabbitMQ Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rabbitmq_health{job=\" booking-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flight Service MSSQL Database Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mssql_db_health{job=\"flight-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airport Service MSSQL Database Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "mssql_db_health{job=\"airport-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EmailService RabbitMQ Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rabbitmq_health{job=\"email-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Service RabbitMQ Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rabbitmq_health{job=\"payment-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}